############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Us"
url = "/about-us"
weight = 2

[[main]]
name = "Our Solution"
url = "/our-solution"
weight = 3

[[main]]
name = "Project Journey"
url = "/project-journey"
weight = 5

[[main]]
weight = 7
name = "Reflections"
url = "/reflections"


# footer menu
